version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx    
    ports:
      - "172.17.0.1:8181:80"
    depends_on:
      - php-fpm
    volumes:
      - wp:/var/www/wp

  php-fpm:
    image: linuxcontainers/wordpress-php-fpm
    volumes:
      - wp:/var/www/wp
    ports:
      - "172.17.0.1:9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "zaC1lZDI1NTE5AA"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "172.17.0.1:3306:3306"
volumes:
        wp:
